i0000008,
{"Title":"Edison Kinetoscopic Record of a Sneeze",
"Year":"1894","Rated":"N/A",
"Released":"09 Jan 1894",
"Runtime":"1 min",
"Genre":"Documentary, Short",
"Director":"William K.L. Dickson",
"Writer":"N/A",
"Actors":"Fred Ott",
"Plot":"A man (Edison's assistant) takes a pinch of snuff and sneezes. This is one of the earliest Edison films and was the first motion picture to be copyrighted in the United States.",
"Language":"N/A",
"Country":"USA",
"Awards":"N/A",
"Poster":"N/A",
"Metascore":"N/A",
"imdbRating":"5.9",
"imdbVotes":"988",
"imdbID":"tt0000008",
"Type":"movie",
"Response":"True"}
